services:
  db_test:
    image: postgres:15
    container_name: csc_postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: csc_test
    ports:
      - "5450:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d csc_test"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
