services:
  - type: web
    name: css-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0. 0.0 --port $PORT --timeout-graceful-shutdown 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: css-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: ENVIRONMENT
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: css-db
    databaseName: css_backend
    user: css_user
    region: frankfurt
    plan: free
